SELECT AUTHORS.AU_ID AS 'AUTHOR ID',
TITLES.TITLE_ID AS 'TITLE ID',
(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS 'ROYALTY_SALES'

FROM AUTHORS

LEFT JOIN TITLEAUTHOR ON TITLEAUTHOR.AU_ID = AUTHORS.AU_ID
LEFT JOIN TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
LEFT JOIN SALES ON SALES.TITLE_ID = TITLES.TITLE_ID
WHERE TITLES.ROYALTY IS NOT NULL
ORDER BY ROYALTY_SALES DESC
;

SELECT AUTHORS.AU_ID AS 'AUTHOR ID',
TITLES.TITLE_ID AS 'TITLE ID',
SUM(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS 'ROYALTY_SALES'

FROM AUTHORS

LEFT JOIN TITLEAUTHOR ON TITLEAUTHOR.AU_ID = AUTHORS.AU_ID
LEFT JOIN TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
LEFT JOIN SALES ON SALES.TITLE_ID = TITLES.TITLE_ID
WHERE TITLES.ROYALTY IS NOT NULL
GROUP BY TITLES.TITLE_ID, AUTHORS.AU_ID
ORDER BY ROYALTY_SALES DESC
;


SELECT AUTHORS.AU_ID AS 'AUTHOR ID',
SUM(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS 'ROYALTY_SALES'

FROM AUTHORS

LEFT JOIN TITLEAUTHOR ON TITLEAUTHOR.AU_ID = AUTHORS.AU_ID
LEFT JOIN TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
LEFT JOIN SALES ON SALES.TITLE_ID = TITLES.TITLE_ID
WHERE TITLES.ROYALTY IS NOT NULL
GROUP BY AUTHORS.AU_ID
ORDER BY ROYALTY_SALES DESC

LIMIT 3
;

CREATE TEMPORARY TABLE TABLE1
SELECT A.AU_ID AS AUTHOR_ID, T.TITLE_ID AS TITLE, (t.price * s.qty * t.royalty / 100 * ta.royaltyper / 100) as ROYALTY_SALES

FROM AUTHORS AS A

LEFT JOIN TITLEAUTHOR AS TA ON A.AU_ID = TA.AU_ID
LEFT JOIN TITLES AS T ON T.TITLE_ID = TA.TITLE_ID
LEFT JOIN SALES AS S ON T.TITLE_ID = S.TITLE_ID
ORDER BY ROYALTY_SALES DESC

;


SELECT AUTHOR_ID, TITLE, ROYALTY_SALES
FROM TABLE1
;

SELECT AUTHOR_ID, ROYALTY_SALES
FROM TABLE1
;

CREATE TABLE most_profiting_authors
SELECT AUTHOR_ID, ROYALTY_SALES AS PROFITS
FROM TABLE1
;